NORMAL_VIDEO_DIRECTORY = './videos/Normal videos'
ANOMALY_VIDEO_DIRECTORY = './videos/Anomaly Videos'
PRE_TRAINED_LSTM_AUTO_ENCODER_PATH = './models/pre_trained_lstm_autoencoder/model.hdf5'
FINE_TUNED_LSTM_AUTO_ENCODER_PATH = './models/pre_trained_lstm_autoencoder/auto_encoder3.hdf5'
TO_PROCESS_VIDEO_FILE_PATH = './videos/Anomaly Videos/Shooting054_x264.mp4'
TO_SAVE_DIRECTORY = './output'
